spring:
  datasource:
    url: jdbc:mysql://centos-vm:3306/db_example?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: toor
#    schema: classpath:db/schema.sql
#    data: classpath:db/data.sql

mybatis:
  # Maven 多模块项目的扫描路径需以 classpath*: 开头 （意思为加载多个 jar 包下的 XML 文件）
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mondari.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.mondari: debug
