spring:
  datasource:
    # 可通过链接 /h2-console 访问 H2 Web控制台
    # 嵌入式链接，数据库文件保存在本地目录～（家目录）下的 test 文件里
    url: jdbc:h2:~/test
  jpa:
    # 不使用 schema.sql 来初始化数据库，使用JPA来初始化
    generate-ddl: false
    # 项目启动时创建数据表，项目结束时删除数据表
    hibernate:
      ddl-auto: create-drop