## 日志配置 ##
#logging:
#  level:
#    root: debug
## 数据源配置 ##
public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIxcXp+q48EDTKDmTyHYQ7t6gMJk2n9HfOMtVtPtuFVmGIGtqoikpLEZoRNRFpGPcVpWyXSdwH51XvNFNPXB+/kCAwEAAQ==
spring:
  jpa:
    # 使用 schema.sql 来初始化数据库
    generate-ddl: true
  datasource:
    url: jdbc:mysql://centos-vm:3306/db_example?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    # password: toor
    # jasypt 加密后的密码
    # password: ENC(lefIojh5L05Z8PPJnwYUGQ==)
    # druid 加密后的密码
    password: ePDKV2Fo+FRnQvSmFIlDJlBgOad9jpB8XbiPAeMxtqinmHmpATxMNNXvG+YBXM93xGTE0haigD27OS8+FMc6CQ==
    # 打开初始化表的开关，默认使用嵌入式数据库才会开启
    initialization-mode: always
    # 使用 Druid 数据库密码加密功能需要一下配置
    druid:
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
      filter:
        config:
          enabled: true

## MyBatis 配置 ##
mybatis:
  # Maven 多模块项目的扫描路径需以 classpath*: 开头 （意思为加载多个 jar 包下的 XML 文件）
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mondari.domain
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  # 可以指定外部配置文件来配置
  # config-location: classpath:mybatis-config.xml

## MyBatis-Plus 配置 ##
mybatis-plus:
  global-config:
    db-config:
      # 配置主键ID自增
      id-type: auto

## PageHelper 分页配置 ##
pagehelper:
  helper-dialect: mysql
  # 分页大小为0时查询所有结果
  page-size-zero: true
  # pageNum<=0 时会查询第一页，pageNum>pages（超过总数时），会查询最后一页
  reasonable: true
